server:
  port: 8011

spring:
  application:
    name: gateway
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      scg:
        fallback:
          mode: response
          response-body: '{"code":400 , "msg":"呜呜呜，您访问的太快了"}'
    #gateway的配置
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':  #允许跨域访问的资源
            allowedOrigins: "*"  #允许跨域来源
            allowedMethods:
              - GET
              - POST
      #路由规则
      routes: #这是一个集合，我们可以配置多个，他是根据id转发到uri
        - id: order_route  #路由的唯一标识 ， 我们路由到order
          uri: lb://order-nacos #需要转发的地址  lb: 使用nacos中的负载均衡策略
          #断言规则，用于路由规则的匹配
          predicates:
            - Path=/order/**  #匹配order-nacos后面以什么开头
            #- After=2023-07-09T17:39:58.431+08:00[Asia/Shanghai] 早于当前时间
            #- Cookie=cook,i  cookie的键值对
            #- Header=header,yangXuG|zhuGeL
            #- CheckAuth=yang

              # http://order-nacos/order-serv/order/add  路由到
              # http://order-nacos/order-serv/order/add

            #过滤器
          #filters:
            #- CheckAuth=yang
            #- RedirectTo=302,https://www.baidu.com/ #重定向到百度
            #- PrefixPath=/mall-order #添加前缀 对应微服务需要配置context‐path
            #- AddRequestHeader=Request‐color,red #添加请求头
            #- StripPrefix=1  #转发之前去掉第一层路径
            # http://localhost:8082/order/add  注意：不能有空格
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos



