server:
  port: 8010

spring:
  application:
   name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
      datasource:
        flow-rule:
          nacos:
            server-addr: 172.16.19.35:8848
            username: nacos
            password: nacos
            data-id: order-sentinel-nacos-flow-rule
            rule-type: flow

