server:
  port: 3050

spring:
  application:
    name: order-openfeign
  cloud:
    nacos:
      server-addr: 172.16.19.35:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        # 相同特征的服务进行归类分组管理
        # ephemeral: false  # 默认=true（临时实例）  当服务宕机 超过心跳 就会将实例剔除掉
        #永久实例   哪怕宕机了也不会删除实例  当服务宕机 永远不会剔除掉
        #group的相同特征的服务进行归类分组管理
        #weight:  通常要结合 安装 权重的负载均衡策略， 权重越高分配的流量就越大
        #metadata: version=1  可以结合元数据做扩展
        #cluster-name: XUSHU


#springBoot默认日志级别是info，feign的默认日志级别是debug
logging:
  level:
    com.java.springCloud.feign: debug

#在yml种指定局部配置feign的日志
feign:
  client:
    config:
      product-service:
        logger-level: BASIC
        #contract: feign.Contract.Default #指定Feign原生注解契约配置
        # 连接超时时间，默认2s
        connectTimeout: 5000
        # 请求处理超时时间，默认5s
        readTimeout: 4000
